apiVersion: v1
kind: Pod
metadata:
  name: har-ambiq-model
spec:
  containers:
  - name: har-ambiq-model
    image: yuy080/har-base-docker2
    resources:
      limits:
        memory: 16Gi      
        cpu: 16
        nvidia.com/gpu: 2           
      requests:
        memory: 16Gi
        cpu: 16
        nvidia.com/gpu: 2           
    command: ["/bin/sh", "-c", "while true; do sleep 1000; done"]
